name: 'practice1_medallion'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  practice1_medallion:
    # Semua model dalam folder staging akan jadi VIEW (Jimat Storage)
    staging:
      +materialized: view
    # Semua model dalam folder bronze akan jadi TABLE (Sebab kita nak simpan Audit Cols)
    bronze:
      +materialized: table